### ISSUE TITLE
Install pybmr-0.7 does not work

### ISSUE THREAD

**Issue by dankeder** [slesinger/pybmr#2]
Hey,

`pip install pybmr` of the most recent pybmr-0.7 does not work:

```
pip install pybmr                                                                                                                                                  ✔  16:19:38  INSERT
Collecting pybmr
  Using cached pybmr-0.7.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dan/.local/apps/python38/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-knxgiioe/pybmr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-knxgiioe/pybmr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rm4dy71o
         cwd: /tmp/pip-install-knxgiioe/pybmr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-knxgiioe/pybmr/setup.py", line 6, in <module>
        with open("requirements.txt") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It is because the package file (pybmr-0.7.tar.gz) uploaded to PyPI doesn't contain the newly added file `requirements.txt`. It should also contain `test-requirements.txt`. Both of them are referenced in `setup.py`. Can you add them please?

**Comment by slesinger** [comment]
Hi, thanks for reporting this. requirements.txt added to package. It works on clear environment.
